name: 🚀 Notify Discord on New Commits

on:
  push:
    branches: [ main, master, develop ]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.NEW_COMMIT }}
          username: "GitHub Commits Bot"
          avatar-url: "https://github.githubassets.com/images/modules/logos_page/Octocat.png"
          embed-title: "🚀 New Commit: ${{ github.event.head_commit.message }}"
          embed-description: |
            **Author:** ${{ github.event.head_commit.author.name }}
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            
            **Commit SHA:** `${{ github.sha }}`
          embed-url: ${{ github.event.head_commit.url }}
          embed-color: 3066993
          embed-timestamp: ${{ github.event.head_commit.timestamp }}